### ISSUE TITLE
Carthage problems

### ISSUE THREAD

**Issue by vytautasgimbutas** [SwiftyBeaver/SBObjectiveCWrapper#7]
My Cartfile looks like this:
```
github "SwiftyBeaver/SwiftyBeaver"
github "SwiftyBeaver/SBObjectiveCWrapper"
```

and I can't install the SBObjectiveCWrapper.

Output:
```
*** Building scheme "SBObjectiveCWrapper (iOS)" in SBObjectiveCWrapper.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/evp/Projects/ios-app-paysera-good/Carthage/Checkouts/SBObjectiveCWrapper/sources/SBObjectiveCWrapper.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/evp/Projects/ios-app-paysera-good/Carthage/Checkouts/SBObjectiveCWrapper/sources/SBObjectiveCWrapper.swift:10:8: error: no such module 'SwiftyBeaver'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64 /Users/evp/Projects/ios-app-paysera-good/Carthage/Checkouts/SBObjectiveCWrapper/sources/SBObjectiveCWrapper.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by skreutzberger** [comment]
Hi, is the issue still existing? I am closing it for now.

**Comment by reesemclean** [comment]
I think so but I am not a big Carthage user so don't have a great sample project to test it out.

**Comment by skreutzberger** [comment]
ok, then let's maybe wait until someone else complains to better verify the issue 😳

**Comment by konstantinbe** [comment]
Just hit a similar issue. After a bit of digging I found the problem:

<img width="252" alt="bildschirmfoto 2017-12-23 um 13 02 33" src="https://user-images.githubusercontent.com/331694/34319397-bf3cc1ee-e7e1-11e7-8222-a90ada04ef2d.png">

On **case-sensitive** file systems this breaks because the path to `sources` is lowercase, while the actual group/folder is uppercase:

<img width="278" alt="bildschirmfoto 2017-12-23 um 13 03 09" src="https://user-images.githubusercontent.com/331694/34319398-c23588ea-e7e1-11e7-8840-c97c3e4be885.png">

**Comment by skreutzberger** [comment]
@konstantinbe Great catch! Can you fix it with a pull request?

**Comment by konstantinbe** [comment]
@skreutzberger I've already submitted one for the main repo. Will do for this one too shortly.
